#print("Hello World")
#print("Salman Khan")
#print(salman khan)
#print(7)
#print(6.7)
#print(True)
#print('Hello',1,4,5,True)
#print('Hello',1,4,5,True,sep='/')
#print('hello',end = '-')
#print('world')
